

export const metadata = {
  title: {
    default: 'Next.js + TypeScript Example',
    template: '%s | Next.js + TypeScript Example',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightgray" }}>Header</header>
        {children}
        <footer style={{ backgroundColor: "lightgray" }}>Footer</footer>
      </body>
    </html>
  );
}
