
export const metadata = {
    title: "My bLogs",
    description: 'Generated by Next.js',
    }
export default function BlogLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
        <h1>My bLogs by layout</h1>
        {children}
    </>
        
      
  );
}
